export const mainColor = '#126BA5'
export const secondaryColor = '#52B6FF'
export const textColor = '#666666'
export const disabled = '#DBDBDB'
export const notDone = '#BABABA'
export const done = '#8FC549'